### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by amino19** [amino19/Health-Tracker#4]
While going through <a href="https://github.com/amino19/Health-Tracker/blob/master/CONTRIBUTING.md"> CONTRIBUTING.md <a> 
- Enhance <a href="https://github.com/amino19/Health-Tracker/blob/master/README.md"> README.md </a> in designing way, so contributors shall get an idea, what's going here.
- Add some badges to looks trendy!

**Tech Stack reqd.** : HTML, Badges digger, Technical English, Documentation

--------
**Resources** 
- <a href="https://dev.to/envoy_/150-badges-for-github-pnk"> Badges </a>
- Prefer any organization `README file` to make it more cool!

**Comment by j-dogcoder** [comment]
This looks like a super cool project! I would love to take this issue to work on!.

**Comment by amino19** [comment]
@j-dogcoder : Here you go! :rocket:

**Comment by j-dogcoder** [comment]
Thanks! I will work on this later today!

**Comment by amino19** [comment]
@j-dogcoder : Yours stage! :slightly_smiling_face:
